### ISSUE TITLE
Provably Robust Boosted Decision Stumps and Trees against Adversarial Attacks

### ISSUE THREAD

**Issue by max-andr** [robust-ml/robust-ml.github.io#13]
**Name**: Provably Robust Boosted Decision Stumps and Trees against Adversarial Attacks

**Authors**: Maksym Andriushchenko, Matthias Hein

**Paper**: https://arxiv.org/abs/1906.03526

**Code**: https://github.com/max-andr/provably-robust-boosting

**Venue**: NeurIPS 2019

**Does the code implement the robust-ml API and include pre-trained models**: yes

**Dataset**: MNIST, FMNIST

**Threat model**: Linf (ϵ=0.3), Linf (ϵ=0.1)

**Natural accuracy**: 97.32%, 85.85% clean accuracy

**Claims**: 87.54%, 76.83% provable accuracy

The pairs of numbers mentioned always correspond to MNIST / FMNIST models respectively.

Thanks.

**Comment by anishathalye** [comment]
Thank you for the submission! It's on the site now: https://www.robust-ml.org/defenses/

I reworded "provable accuracy" to "certified" for consistency with other items in the table.
